import { Event, Category } from "./types";

export const categories: Category[] = [
  {
    id: "technical",
    name: "Technical",
    icon: "💻",
    description: "Challenge your technical skills",
  },
  {
    id: "competitions",
    name: "Competitions",
    icon: "🏆",
    description: "Compete to win",
  },
];

export const events: Event[] = [
  {
    id: 1,
    title: "E-Sports",
    description:
      "Compete in thrilling online games across two exciting events.",
    date: "March 16, 2025",
    prize: "₹45,000",
    image: "https://picsum.photos/seed/esports/800/600",
    category: "competitions",
    fees: "₹250 per team",
    building: "Auditorium Block",
    venue: "Gaming Arena, Ground Floor",
    highlights: [
      "Two game categories",
      "Professional gaming setups",
      "Cash prizes for top 3 teams",
    ],
    timeline: [
      "9:00 AM - Registration",
      "10:00 AM - Game 1 Begins",
      "2:00 PM - Game 2 Finals",
      "5:00 PM - Winner Announcement",
    ],
    requirements: [
      "Team of 4-6 players",
      "Bring your own peripherals",
      "Student ID required",
    ],
    rules: [
      "Team size of 4-6 players",
      "Game-specific rules will apply",
      "Fair play is mandatory",
      "Judges' decisions are final",
    ],
    coordinators: [
      {
        name: "Ravi Kumar",
        phone: "+91 9876543214",
        email: "ravi.kumar@college.edu",
      },
      {
        name: "Priya Sharma",
        phone: "+91 9876543215",
        email: "priya.sharma@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/esports.png",
  },
  {
    id: 2,
    title: "Hackathon",
    description: "24-hour coding challenge to solve real-world problems.",
    date: "March 15, 2025",
    prize: "₹35,500",
    image: "https://picsum.photos/seed/hackathon/800/600",
    category: "technical",
    fees: "₹500 per team",
    building: "Computer Science Block",
    venue: "Lab 401, 4th Floor",
    highlights: [
      "24 Hours of Coding",
      "Industry Mentors",
      "Networking Opportunities",
      "Exciting Prizes",
    ],
    timeline: [
      "10:00 AM - Registration",
      "11:00 AM - Opening Ceremony",
      "12:00 PM - Coding Begins",
      "Next Day 12:00 PM - Submission",
      "2:00 PM - Results",
    ],
    requirements: [
      "Team of 2-4 members",
      "Laptop with required software",
      "Student ID required",
    ],
    rules: [
      "Team size between 2-4",
      "All team members must be students",
      "No pre-built solutions",
      "Judges' decision is final",
    ],
    coordinators: [
      {
        name: "Aditi Verma",
        phone: "+91 9876543216",
        email: "aditi.verma@college.edu",
      },
      {
        name: "Karan Singh",
        phone: "+91 9876543217",
        email: "karan.singh@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/hackathon.png",
  },
  {
    id: 3,
    title: "Ode to Code",
    description:
      "A coding contest to test your logical and problem-solving skills.",
    date: "March 17, 2025",
    prize: "₹22,500",
    image: "https://picsum.photos/seed/code/800/600",
    category: "technical",
    fees: "₹300 per participant",
    building: "Computer Science Block",
    venue: "Lab 402, 4th Floor",
    highlights: [
      "Challenging Problems",
      "Individual Participation",
      "Exciting Cash Prizes",
    ],
    timeline: [
      "10:00 AM - Reporting",
      "10:30 AM - Round 1",
      "2:00 PM - Round 2",
      "5:00 PM - Results",
    ],
    requirements: ["Student ID", "Laptop with required IDEs"],
    rules: [
      "Individual participation only",
      "Any programming language allowed",
      "Judges' decision is final",
    ],
    coordinators: [
      {
        name: "Vikas Mehta",
        phone: "+91 9876543218",
        email: "vikas.mehta@college.edu",
      },
      {
        name: "Meera Iyer",
        phone: "+91 9876543219",
        email: "meera.iyer@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/ode-to-code.png",
  },
  {
    id: 4,
    title: "Bike and Car Expo",
    description:
      "A stunning display of innovation and creativity in automobiles.",
    date: "March 18, 2025",
    prize: "No prizes",
    image: "https://picsum.photos/seed/bikeandcar/800/600",
    category: "competitions",
    fees: "₹100",
    building: "Mechanical Block",
    venue: "Open Ground Area",
    highlights: [
      "Custom-built bikes and cars",
      "Live demonstrations",
      "Networking with enthusiasts",
    ],
    timeline: [
      "10:00 AM - Setup",
      "12:00 PM - Expo Opens",
      "5:00 PM - Expo Closes",
    ],
    requirements: ["Registered vehicle details", "Proof of ownership"],
    rules: [
      "No illegal modifications allowed",
      "Vehicles must meet safety standards",
      "Organizers' decision is final",
    ],
    coordinators: [
      {
        name: "Anil Kapoor",
        phone: "+91 9876543220",
        email: "anil.kapoor@college.edu",
      },
      {
        name: "Sonal Gupta",
        phone: "+91 9876543221",
        email: "sonal.gupta@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/bikeexpo.png",
  },
  {
    id: 5,
    title: "Robo Olympics",
    description: "Compete in robotic challenges across three events.",
    date: "March 19, 2025",
    prize: "₹1,00,000",
    image: "https://picsum.photos/seed/robo/800/600",
    category: "technical",
    fees: "₹1,000 per team",
    building: "Robotics Lab",
    venue: "Arena 101, Robotics Block",
    highlights: ["3 Unique Events", "Exciting Prizes", "Innovative Challenges"],
    timeline: [
      "10:00 AM - Registration",
      "11:00 AM - Event 1",
      "2:00 PM - Event 2",
      "4:00 PM - Event 3 Finals",
    ],
    requirements: ["Team of 2-4 members", "Custom-built robots"],
    rules: [
      "Robots must meet size and weight limits",
      "No pre-built kits allowed",
      "Judges' decision is final",
    ],
    coordinators: [
      {
        name: "Rahul Nair",
        phone: "+91 9876543222",
        email: "rahul.nair@college.edu",
      },
      {
        name: "Neha Jain",
        phone: "+91 9876543223",
        email: "neha.jain@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/robo.png",
  },
  {
    id: 6,
    title: "Dronix",
    description: "Show off your drone skills and compete for prizes.",
    date: "March 20, 2025",
    prize: "₹45,000",
    image: "https://picsum.photos/seed/dronix/800/600",
    category: "technical",
    fees: "₹500 per team",
    building: "Aeronautics Block",
    venue: "Drone Field, Ground Floor",
    highlights: ["Obstacle Course", "Precision Challenges", "Live Audience"],
    timeline: [
      "10:00 AM - Registration",
      "11:00 AM - Round 1",
      "2:00 PM - Final Round",
    ],
    requirements: ["Custom-built or commercial drones", "Battery backups"],
    rules: [
      "Drone size must meet regulations",
      "Only one team member can operate the drone",
      "Judges' decision is final",
    ],
    coordinators: [
      {
        name: "Pooja Reddy",
        phone: "+91 9876543224",
        email: "pooja.reddy@college.edu",
      },
      {
        name: "Amit Desai",
        phone: "+91 9876543225",
        email: "amit.desai@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/dronix.png",
  },
  {
    id: 7,
    title: "Bridge Mania",
    description:
      "Design and construct model bridges that can withstand maximum weight.",
    date: "March 20, 2025",
    prize: "₹22,500",
    image: "https://picsum.photos/seed/bridge/800/600",
    category: "technical",
    fees: "₹400 per team",
    building: "Civil Engineering Block",
    venue: "Hall 201, 2nd Floor",
    highlights: [
      "Hands-on bridge building",
      "Weight testing on models",
      "Exciting prizes for winners",
    ],
    timeline: [
      "10:00 AM - Registration",
      "11:00 AM - Model Building",
      "3:00 PM - Load Testing",
      "5:00 PM - Results",
    ],
    requirements: [
      "Team of 2-4 members",
      "Basic construction tools",
      "Student ID",
    ],
    rules: [
      "All materials must be eco-friendly",
      "Bridge must meet size constraints",
      "Judges' decisions are final",
    ],
    coordinators: [
      {
        name: "Rajesh Patil",
        phone: "+91 9876543226",
        email: "rajesh.patil@college.edu",
      },
      {
        name: "Suhana Roy",
        phone: "+91 9876543227",
        email: "suhana.roy@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/bridge-mania.png",
  },
  {
    id: 8,
    title: "India Innovates",
    description:
      "A showcase of innovative projects solving real-world problems.",
    date: "March 21, 2025",
    prize: "₹22,500",
    image: "https://picsum.photos/seed/innovates/800/600",
    category: "technical",
    fees: "₹300 per project",
    building: "Innovation Block",
    venue: "Exhibition Hall, Ground Floor",
    highlights: [
      "Project displays",
      "Networking opportunities",
      "Exciting cash prizes",
    ],
    timeline: [
      "9:00 AM - Setup",
      "10:00 AM - Exhibition Opens",
      "4:00 PM - Judging",
      "5:00 PM - Winners Announced",
    ],
    requirements: [
      "Innovative project",
      "Presentation board or poster",
      "Working prototype (if applicable)",
    ],
    rules: [
      "Projects must be original",
      "Judging criteria: innovation, impact, and feasibility",
      "Judges' decision is final",
    ],
    coordinators: [
      {
        name: "Ananya Khanna",
        phone: "+91 9876543228",
        email: "ananya.khanna@college.edu",
      },
      {
        name: "Arjun Deshmukh",
        phone: "+91 9876543229",
        email: "arjun.deshmukh@college.edu",
      },
    ],
    qrCode: "/images/payment-qr/india-innovates.png",
  },
];
