import { Event, Category } from "./types";

export const categories: Category[] = [
  {
    id: "technical",
    name: "Technical",
    icon: "💻",
    description: "Challenge your technical skills",
  },
  {
    id: "cultural",
    name: "Cultural",
    icon: "🎭",
    description: "Showcase your creativity",
  },
  {
    id: "workshops",
    name: "Workshops",
    icon: "🔧",
    description: "Learn from experts",
  },
  {
    id: "competitions",
    name: "Competitions",
    icon: "🏆",
    description: "Compete to win",
  },
];

export const events: Event[] = [
  {
    id: 1,
    title: "Hackathon",
    description: "24-hour coding challenge to solve real-world problems",
    date: "March 15, 2025",
    prize: "₹50,000",
    image: "https://picsum.photos/seed/hackathon/800/600",
    category: "technical",
    featured: true,
    highlights: [
      "24 Hours of Coding",
      "Industry Mentors",
      "Amazing Prizes",
      "Networking Opportunities",
    ],
    timeline: [
      "10:00 AM - Registration",
      "11:00 AM - Opening Ceremony",
      "12:00 PM - Coding Begins",
      "Next Day 12:00 PM - Submission",
      "2:00 PM - Results",
    ],
    requirements: [
      "Laptop with required software",
      "Student ID",
      "Team of 2-4 members",
    ],
  },
  {
    id: 2,
    title: "Competitive Programming",
    description: "Test your algorithmic skills against the best",
    date: "March 14, 2025",
    prize: "₹30,000",
    image: "https://picsum.photos/seed/coding/800/600",
    category: "technical",
    highlights: [
      "Individual Competition",
      "Multiple Rounds",
      "Live Leaderboard",
      "Problem Setting by Experts",
    ],
    timeline: [
      "9:00 AM - Reporting Time",
      "10:00 AM - Round 1",
      "2:00 PM - Round 2",
      "5:00 PM - Final Round",
    ],
    requirements: [
      "Laptop",
      "Student ID",
      "Knowledge of any programming language",
    ],
  },
  {
    id: 3,
    title: "Cultural Night",
    description: "A celebration of music, dance, and theatrical performances",
    date: "March 16, 2025",
    prize: "₹25,000",
    image: "https://picsum.photos/seed/cultural/800/600",
    category: "cultural",
    featured: true,
    highlights: [
      "Live Performances",
      "Celebrity Guest",
      "Professional Sound System",
      "Open for All",
    ],
    timeline: [
      "6:00 PM - Gates Open",
      "7:00 PM - Opening Act",
      "8:00 PM - Main Performances",
      "10:00 PM - Closing Ceremony",
    ],
  },
  {
    id: 4,
    title: "Robotics Workshop",
    description: "Learn to build and program your own robot",
    date: "March 14, 2025",
    prize: "Certificate",
    image: "https://picsum.photos/seed/robotics/800/600",
    category: "workshops",
    highlights: [
      "Hands-on Experience",
      "Take Home Kit",
      "Industry Expert Sessions",
      "Project Building",
    ],
    timeline: [
      "9:00 AM - Introduction",
      "10:30 AM - Basic Electronics",
      "2:00 PM - Programming Session",
      "4:00 PM - Project Work",
    ],
    requirements: [
      "Basic knowledge of electronics",
      "Laptop",
      "Registration fee payment",
    ],
  },
  {
    id: 5,
    title: "Dance Competition",
    description: "Showcase your dance moves across various styles",
    date: "March 15, 2025",
    prize: "₹20,000",
    image: "https://picsum.photos/seed/dance/800/600",
    category: "cultural",
    highlights: [
      "Solo & Group Categories",
      "Professional Judges",
      "Multiple Dance Styles",
      "Live Audience",
    ],
    timeline: [
      "11:00 AM - Preliminary Round",
      "2:00 PM - Semi Finals",
      "5:00 PM - Finals",
      "6:00 PM - Prize Distribution",
    ],
  },
  {
    id: 6,
    title: "AI/ML Workshop",
    description: "Deep dive into artificial intelligence and machine learning",
    date: "March 14, 2025",
    prize: "Certificate & Toolkit",
    image: "https://picsum.photos/seed/ai/800/600",
    category: "workshops",
    featured: true,
    highlights: [
      "Industry Expert Training",
      "Hands-on Projects",
      "Dataset Access",
      "Career Guidance",
    ],
    timeline: [
      "9:00 AM - Basics of AI/ML",
      "11:00 AM - Python Programming",
      "2:00 PM - Model Building",
      "4:00 PM - Project Implementation",
    ],
    requirements: [
      "Basic Python knowledge",
      "Laptop with minimum 8GB RAM",
      "Prerequisites software installation",
    ],
  },
  {
    id: 7,
    title: "Gaming Tournament",
    description: "Compete in popular esports titles",
    date: "March 15-16, 2025",
    prize: "₹40,000",
    image: "https://picsum.photos/seed/gaming/800/600",
    category: "competitions",
    highlights: [
      "Multiple Game Titles",
      "Professional Setup",
      "Live Streaming",
      "Experienced Referees",
    ],
    timeline: [
      "Day 1 - Qualifiers",
      "Day 1 Evening - Quarter Finals",
      "Day 2 - Semi Finals",
      "Day 2 Evening - Finals",
    ],
    requirements: [
      "Own gaming peripherals",
      "Team registration",
      "Game-specific requirements",
    ],
  },
  {
    id: 8,
    title: "Web Development",
    description: "Create modern web applications with latest technologies",
    date: "March 14, 2025",
    prize: "₹25,000",
    image: "https://picsum.photos/seed/webdev/800/600",
    category: "technical",
    highlights: [
      "Full Stack Development",
      "Modern Frameworks",
      "Real-world Projects",
      "Industry Standards",
    ],
    timeline: [
      "10:00 AM - Frontend Basics",
      "12:00 PM - Backend Integration",
      "2:00 PM - Database Management",
      "4:00 PM - Deployment",
    ],
  },
  {
    id: 9,
    title: "Photography Contest",
    description: "Capture moments and tell stories through your lens",
    date: "March 14-16, 2025",
    prize: "₹15,000",
    image: "https://picsum.photos/seed/photo/800/600",
    category: "cultural",
    highlights: [
      "Multiple Categories",
      "Professional Judging",
      "Exhibition Opportunity",
      "Equipment Showcase",
    ],
    timeline: [
      "Day 1 - Theme Announcement",
      "Day 1-2 - Shooting Period",
      "Day 3 Morning - Submission",
      "Day 3 Evening - Results",
    ],
  },
  {
    id: 10,
    title: "Startup Pitch",
    description: "Present your innovative ideas to investors",
    date: "March 16, 2025",
    prize: "₹1,00,000",
    image: "https://picsum.photos/seed/startup/800/600",
    category: "competitions",
    featured: true,
    highlights: [
      "Real Investors",
      "Mentorship Sessions",
      "Networking Events",
      "Funding Opportunities",
    ],
    timeline: [
      "9:00 AM - Registration",
      "10:00 AM - Preliminary Pitches",
      "2:00 PM - Final Pitches",
      "4:00 PM - Awards Ceremony",
    ],
    requirements: [
      "Business Plan",
      "Presentation Deck",
      "Working Prototype (if applicable)",
    ],
  },
];
